trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    'robot -d ./logs tests/iphone_search.robot'
  displayName: 'Run Robot Framework Tests'

- script: |
    robot tests
  displayName: 'Run Robot Framework Tests'