jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nfqlt/chromedriver:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python and pip
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        python3 -m pip install --upgrade pip
    - name: Install Dependencies
      run: |
        pip install robotframework
        pip install --upgrade robotframework-seleniumlibrary
        pip install robotframework-requests
    - name: Make scripts executable
      run: |
        chmod +x tests/*.robot
    - name: Run Tests
      working-directory: ./tests
      run: |
        robot -d ../logs iphone_search.robot
