name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nfqlt/chromedriver:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python and pip
      run: |
         apt install python3-xyz
    - name: Install Dependencies
      run: |
        pip install robotframework
        pip install --upgrade robotframework-seleniumlibrary
        pip install robotframework-requests
    - name: Make scripts executable
      run: |
        chmod +x tests/*.robot
    - name: Run Tests
      working-directory: ./tests
      run: |
        robot -d ../logs iphone_search.robot
