name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install --upgrade robotframework-seleniumlibrary
        pip install webdrivermanager
        webdrivermanager firefox chrome --linkpath /usr/local/bin
        pip install robotframework-requests

    - name: Run Tests
      run: |
        robot -d ./logs tests/iphone_search.robot
