name: Teste com robot framework

on: workflow_dispatch

jobs:
  run_automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependecies
      env:
        PYTHON_VERSION: "3.12"
      run: |
        py_version=$PYTHON_VERSION
        sudo apt update
        sudo apt install python"$py_version"
    - name: Verify Version
      run: |
          python --version
    - name: Install libraries for robot
      run: |
          pip install -U pip
          pip install --upgrade robotframework
          pip install --upgrade selenium==4.9.1
          pip install -r requirements.txt
    - name: Run Tests
      run: |
            mkdir results
            robot -d ./logs tests/iphone_search.robot
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: reports
        