name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install WebDriverManager
      run: pip install webdrivermanager

    - name: Configure Selenium
      run: |
        echo "Caminho atual: $PATH"
        webdrivermanager chrome --linkpath C:\chromedriver\chromedriver.exe

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        robot -d ./logs tests/iphone_search.robot