name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: nfqlt/chromedriver:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python and pip
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        python3 -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        pip install robotframework
        pip install --upgrade robotframework-seleniumlibrary
        pip install robotframework-requests

    - name: Run Tests
      run: |
        robot -d ./logs tests/iphone_search.robot
