name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chromedriver
       run: |
        # Get the latest Chromedriver version
        $latest_version = (Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/LATEST_RELEASE).Content.Trim()

        # Download and extract Chromedriver
        $url = "https://chromedriver.storage.googleapis.com/$latest_version/chromedriver_win32.zip"
        Invoke-WebRequest -Uri $url -OutFile chromedriver.zip
        Expand-Archive -Path chromedriver.zip -DestinationPath $env:ProgramFiles
        Remove-Item chromedriver.zip

        # Add Chromedriver to the PATH
        $env:Path += ";$env:ProgramFiles\chromedriver_win32"
        
    - name: Run Tests
      run: |
        robot -d ./logs tests/iphone_search.robot
