name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chromedriver
      run: |
        # Download and extract Chromedriver
        Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/120.0.6099.109/chromedriver_win32.zip -OutFile chromedriver.zip
        Expand-Archive -Path chromedriver.zip -DestinationPath $env:ProgramFiles
        Remove-Item chromedriver.zip

        # Add Chromedriver to the PATH
        $env:Path += ";$env:ProgramFiles\chromedriver_win32"

    - name: Run Tests
      run: |
        robot -d ./logs tests/iphone_search.robot
